# Generated by Django 4.2.4 on 2023-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_squashed_0004_choice_created_at_choice_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
