# Generated by Django 4.2.4 on 2023-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_choice_created_at_alter_question_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("photo", models.ImageField(upload_to="cars")),
                ("specs", models.FileField(upload_to="specs")),
            ],
        ),
    ]
